config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources  :achievements do
    resources :encouragements, only: [:new, :create]
  end

  namespace :api do
    resources :achievements, only: [ :index ]
  end

  root to: 'welcome#index'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
    belongs_to :user, optional: true #association
    
    validates :title, presence: true
    validates :title, uniqueness: {
        scope: :user_id,
        message: "you can't have two achievements with the same title"
    }

    enum privacy: [:public_access, :private_access, :friends_access]

    mount_uploader :cover_image, CoverImageUploader

    def description_html
        Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
    end

    def test_title
        "#{title} by #{user.email}"
    end

    def self.by_letter(letter)
        includes(:user).where("title LIKE?", "#{letter}%").order("users.email")
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :destroy, :update]
    before_action :owners_only, only: [:edit, :update, :destroy] #to declare function owners_only

    def new
        @achievement = Achievement.new
    end

    def create
        @achievement = Achievement.new(achievement_params)
        @achievement.user = current_user
        if @achievement.save
            UserMailer.achievement_created(current_user.email, @achievement.id).deliver_now
            # tweet = TwitterService.new.tweet(@achievement.title)
            redirect_to achievement_url(@achievement), notice: "Achievement has been created. We tweeted for you!"
        else
            render :new
        end
    end

    def index
        @achievements = Achievement.public_access
    end

    def show
        @achievement = Achievement.find(params[:id])
    end

    def edit   
    end

    def update
        if @achievement.update_attributes(achievement_params)
            redirect_to achievement_path(@achievement)
        else
            render :edit
        end
    end

    def destroy
        @achievement.destroy
        redirect_to achievements_path
    end

    private
    
    def achievement_params
        params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :featured)
    end

    def owners_only 
        @achievement = Achievement.find(params[:id])
        if current_user != @achievement.user
            redirect_to achievements_path
        end
    end
end

app/controllers/api/achievements_controller.rb
class Api::AchievementsController < ApiController
    def index
        achievements = Achievement.public_access
        render json: achievements
    end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
    protect_from_forgery with: :null_session

    # before_action :validate_header

    private

    # def validate_header
    #   if request.headers["Content-Type"] != 'application/vnd.api+json'
    #     render json: {}, status: 200
    #     return 
    #   end
    # end
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/encouragements_controller.rb
class EncouragementsController < ApplicationController

    def new
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/achievements/new.html.erb
<%= simple_form_for @achievement, :html=> { class: 'form-horizontal' } do |f| %>
    <div class="form-horizontal">
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :privacy, collection: Hash[Achievement.privacies.map {|k,v| [k.split('_').first.capitalize, k]}] %>
        <%= f.input :featured, label: "Featured achievement" %>
        <%= f.input :cover_image, as: :file, label: "Cover Image" %>

        <%= f.submit 'Create achievement', class:"btn btn-primary" %>
    </div>
<% end %>

app/views/achievements/show.html.erb
<%= @achievement.title %>
<div>
<%= @achievement.description_html.html_safe %>
</div>

<div class="encouragement">
    <h2>Encouragements</h2>
    <%= link_to "Encourage", new_achievement_encouragement_path(@achievement), id: "encourage-button" %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingWithRuby</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Testing With Ruby</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><%= link_to 'New Achievement', new_achievement_path %></li>
      </div>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </div>
  
  </body>

</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>